// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FriendTab.Resource", IsApplication=true)]

namespace FriendTab
{
	
	
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aitemborder = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int aitemfooter = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int aitemring = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bottom_divider_glow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int box = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int boxdrag = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int flashbar = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int flashbar_button = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int flashbar_button_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int flashbar_button_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int flashbar_divider = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int gmaps = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int header = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_contact_picture = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_menu_refresh = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int LandingBackground = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int top_divider_glow = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int whitering = 2130837522;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070033
			public const int ActionButton = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int ActionSecondButton = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int BadgeIcon = 2131165237;
			
			// aapt resource value: 0x7f070039
			public const int BadgeSubtitle = 2131165241;
			
			// aapt resource value: 0x7f070038
			public const int BadgeTitle = 2131165240;
			
			// aapt resource value: 0x7f070010
			public const int BottomGlow = 2131165200;
			
			// aapt resource value: 0x7f070018
			public const int CompletionList = 2131165208;
			
			// aapt resource value: 0x7f070004
			public const int ContactName = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int ContactPicture = 2131165187;
			
			// aapt resource value: 0x7f07001a
			public const int EmailEntry = 2131165210;
			
			// aapt resource value: 0x7f070005
			public const int HeaderSeparator = 2131165189;
			
			// aapt resource value: 0x7f070031
			public const int InformativeText = 2131165233;
			
			// aapt resource value: 0x7f070007
			public const int ItemPicture = 2131165191;
			
			// aapt resource value: 0x7f070019
			public const int LandingBackground = 2131165209;
			
			// aapt resource value: 0x7f070012
			public const int LoadingContent = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int LocationEntry = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int LocationProgress = 2131165207;
			
			// aapt resource value: 0x7f070009
			public const int MapPicture = 2131165193;
			
			// aapt resource value: 0x7f070013
			public const int NoContent = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int NoneText = 2131165206;
			
			// aapt resource value: 0x7f07001b
			public const int PasswordEntry = 2131165211;
			
			// aapt resource value: 0x7f07003b
			public const int RefreshAction = 2131165243;
			
			// aapt resource value: 0x7f07001c
			public const int SignInButton = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int SignUpButton = 2131165213;
			
			// aapt resource value: 0x7f070032
			public const int Spinner = 2131165234;
			
			// aapt resource value: 0x7f07002a
			public const int StatsLoadSpinner = 2131165226;
			
			// aapt resource value: 0x7f070037
			public const int TapInfoLayout = 2131165239;
			
			// aapt resource value: 0x7f070036
			public const int TapInset = 2131165238;
			
			// aapt resource value: 0x7f070000
			public const int TopGlow = 2131165184;
			
			// aapt resource value: 0x7f070020
			public const int animatedLayout = 2131165216;
			
			// aapt resource value: 0x7f070026
			public const int arrowWay = 2131165222;
			
			// aapt resource value: 0x7f07000c
			public const int atStatic = 2131165196;
			
			// aapt resource value: 0x7f07002c
			public const int categoryPlaceholder = 2131165228;
			
			// aapt resource value: 0x7f07002e
			public const int flashbar = 2131165230;
			
			// aapt resource value: 0x7f070030
			public const int flashbar_button = 2131165232;
			
			// aapt resource value: 0x7f07002f
			public const int flashbar_message = 2131165231;
			
			// aapt resource value: 0x7f070006
			public const int frameLayout1 = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int frameLayout3 = 2131165194;
			
			// aapt resource value: 0x7f07003a
			public const int karmaBar = 2131165242;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout1 = 2131165186;
			
			// aapt resource value: 0x7f07001e
			public const int linearLayout2 = 2131165214;
			
			// aapt resource value: 0x7f07000d
			public const int locationInfo = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int mainFrame = 2131165185;
			
			// aapt resource value: 0x7f07000f
			public const int onStatic = 2131165199;
			
			// aapt resource value: 0x7f070025
			public const int otherFace = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int otherFaceLayout = 2131165220;
			
			// aapt resource value: 0x7f07000b
			public const int relativeLayout1 = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int secondaryFrame = 2131165192;
			
			// aapt resource value: 0x7f070028
			public const int selfFace = 2131165224;
			
			// aapt resource value: 0x7f070027
			public const int selfFaceLayout = 2131165223;
			
			// aapt resource value: 0x7f070011
			public const int space1 = 2131165201;
			
			// aapt resource value: 0x7f07002d
			public const int testInset = 2131165229;
			
			// aapt resource value: 0x7f070015
			public const int textView2 = 2131165205;
			
			// aapt resource value: 0x7f07001f
			public const int textView3 = 2131165215;
			
			// aapt resource value: 0x7f07000e
			public const int timeInfo = 2131165198;
			
			// aapt resource value: 0x7f070022
			public const int userBadge = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int userFacesLayout = 2131165219;
			
			// aapt resource value: 0x7f070029
			public const int whatEntry = 2131165225;
			
			// aapt resource value: 0x7f07002b
			public const int whatLayout = 2131165227;
			
			// aapt resource value: 0x7f070021
			public const int whoLayout = 2131165217;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityItemLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActivityLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AskLocationLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ParticipantSelectionLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SignupPage = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TapBadge = 2130903046;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_menu = 2131099648;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int flashbar_stats_error = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int flashbar_tab_error = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int invalid_email = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int login_error = 2130968577;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int FlashBar = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int FlashBarButton = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int FlashBarMessage = 2131034113;
			
			private Style()
			{
			}
		}
	}
}
